// Generated by bench2verilog.py
module adder_3_bit(
    Cout, S
);

  output Cout, S;
  wire   _const_0, _const_1;

  assign Cout = _const_0;
  assign S = _const_0;
  assign _const_0 = 0;
  assign _const_1 = 1;

endmodule
